#pragma once
#include "SoundSystem.h"

namespace soundEffects
{
	DAE_SOUND_VAR(BLOCK_BREAK);
	DAE_SOUND_VAR(BLOCK_STOP);
	DAE_SOUND_VAR(PLAYER_CLEAR);
	DAE_SOUND_VAR(PLAYER_DEATH);
	DAE_SOUND_VAR(PLAYER_LOSE);
	DAE_SOUND_VAR(PLAYER_START);
	DAE_SOUND_VAR(SNOBEE_DEATH);
	DAE_SOUND_VAR(SONG);
	DAE_SOUND_VAR(BUTTON_HOVER);
	DAE_SOUND_VAR(BUTTON_CLICK);
};
